version: '3'

services:
  miner:
    build:
      context: .
      dockerfile: ./code/miner/Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    restart: always

  bot:
    build:
      context: .
      dockerfile: ./code/bot/Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    restart: always

  # TODO: Add cleaner later
  # cleaner:
  #   build:
  #     context: .
  #     dockerfile: ./code/cleaner/Dockerfile
  #   environment:
  #     - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
  #   restart: always
