version: '3'

services:
  miner:
    build:
      context: .
      dockerfile: ./miner/Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    restart: always

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    restart: always

  cleaner:
    build:
      context: .
      dockerfile: ./cleaner/Dockerfile
    environment:
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    restart: always
