version: '3'

services:
  miner:
    build:
      context: ./miner
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    ports:
      - "8080:80"
    restart: always

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    ports:
      - "8081:80"
    restart: always

  cleaner:
    build:
      context: ./cleaner
      dockerfile: Dockerfile
    environment:
      - POSTGRES_CONNECTION_URI=${POSTGRES_CONNECTION_URI}
    ports:
      - "8082:80"
    restart: always